version: '3.3'
services:
  springappdemo:
    build:
      context: .
    ports:
      - 8000:8000
      - 8080:8080
    environment:
      - SERVER_PORT=8080
    volumes:
      - ./:/app
    command: ./mvnw spring-boot:run -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"

  postgresDB:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=demoDB
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgres
      - postgres_config:/etc/postgres/conf.d
volumes:
  postgres_data:
  postgres_config:
